version: 2
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Authorize GCloud Command Line Tool
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account --key-file=jordan-playground-306709-e0fc53a3e506.json
      - run:
          name: Deploy To Google Cloud Functions
          command: |
            # Move into directory
            cd ../functions/sendAlertLinkedin
            # Variables
            FUNCTION_NAME=sendAlertLinkedin
            ENTRYPOINT=sendAlertLinkedin
            GCP_PROJECT=jordan-playground
            # Deploy command
            gcloud functions deploy $FUNCTION_NAME \
              --entry-point $ENTRYPOINT \
              --runtime nodejs10 \
              --trigger-http \
              --region europe-west1 \
              --allow-unauthenticated \
              --project $GCP_PROJECT
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master